[project]
name = "mcp-lambda"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.30",
    "langchain-core>=1.2.7",
    "langgraph>=1.0.6",
    "mcp>=1.25.0",
    "starlette>=0.52.1",
    "uvicorn>=0.40.0",
]
